# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
  - &OrdererOrg
    Name: OrdererOrg
    ID: OrdererOrgMSP
    MSPDir: ../organizations/ordererOrganizations/ordererorg.example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererOrgMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererOrgMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererOrgMSP.admin')"
    OrdererEndpoints:
      - orderer.ordererorg.example.com:7050
  - &Central
    Name: CentralMSP
    ID: CentralMSP
    MSPDir: ../organizations/peerOrganizations/central.example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('CentralMSP.admin', 'CentralMSP.peer', 'CentralMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('CentralMSP.admin', 'CentralMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('CentralMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('CentralMSP.peer')"
  - &a1
    Name: a1MSP
    ID: a1MSP
    MSPDir: ../organizations/peerOrganizations/a1.example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('a1MSP.admin', 'a1MSP.peer', 'a1MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('a1MSP.admin', 'a1MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('a1MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('a1MSP.peer')"
  - &b1
    Name: b1MSP
    ID: b1MSP
    MSPDir: ../organizations/peerOrganizations/b1.example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('b1MSP.admin', 'b1MSP.peer', 'b1MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('b1MSP.admin', 'b1MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('b1MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('b1MSP.peer')"
################################################################################
#
#   SECTION: Capabilities
#
################################################################################
Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_5: true

################################################################################
#
#   SECTION: Application
#
################################################################################
Application: &ApplicationDefaults
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
  Capabilities:
    <<: *ApplicationCapabilities

################################################################################
#
#   SECTION: Orderer
#
################################################################################
Orderer: &OrdererDefaults
  OrdererType: etcdraft
  Addresses:
    - orderer.ordererorg.example.com:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"
  EtcdRaft:
    Consenters:
    - Host: orderer.ordererorg.example.com
      Port: 7050
      ClientTLSCert: ../organizations/ordererOrganizations/ordererorg.example.com/orderers/orderer.ordererorg.example.com/tls/server.crt
      ServerTLSCert: ../organizations/ordererOrganizations/ordererorg.example.com/orderers/orderer.ordererorg.example.com/tls/server.crt
  Capabilities:
    <<: *OrdererCapabilities

################################################################################
#
#   CHANNEL
#
################################################################################
Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities

################################################################################
#
#   Profile
#
################################################################################
Profiles:
  ChannelUsingRaft:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *Central
        - *a1
        - *b1
      Capabilities: *ApplicationCapabilities
