version: '3.7'

networks:
  fabric_network:
    name: fabric_network
    external: true

services:
  ca_central_bank:
    image: hyperledger/fabric-ca:latest
    container_name: ca_central_bank
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-central-bank
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17054
      # 管理员用户的用户名和密码
      - FABRIC_CA_SERVER_ADMIN_USER=admin
      - FABRIC_CA_SERVER_ADMIN_PASSWORD=adminpw
    ports:
      - "7054:7054" # CA服务端口
      - "17054:17054" # 操作服务端口
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-ca/central_bank:/etc/hyperledger/fabric-ca-server
    networks:
      - fabric_network

  ca_bank1:
    image: hyperledger/fabric-ca:latest
    container_name: ca_bank1
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-bank1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=8054
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:18054
      - FABRIC_CA_SERVER_ADMIN_USER=admin
      - FABRIC_CA_SERVER_ADMIN_PASSWORD=adminpw
    ports:
      - "8054:8054"
      - "18054:18054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-ca/bank1:/etc/hyperledger/fabric-ca-server
    networks:
      - fabric_network

  ca_bank2:
    image: hyperledger/fabric-ca:latest
    container_name: ca_bank2
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-bank2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=9054
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:19054
      - FABRIC_CA_SERVER_ADMIN_USER=admin
      - FABRIC_CA_SERVER_ADMIN_PASSWORD=adminpw
    ports:
      - "9054:9054"
      - "19054:19054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-ca/bank2:/etc/hyperledger/fabric-ca-server
    networks:
      - fabric_network
