#
# 此文件由 generate-configtx.sh 脚本自动生成
# 基于 configtx/network-config.json 配置文件
# 请勿手动修改此文件！如需更改请修改 network-config.json 后重新生成
# 生成时间: 2025-06-23 16:49:43
#

# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   银行数字货币网络配置文件
#   自动生成 - 请勿手动修改
#
################################################################################

################################################################################
#
#   组织定义
#
################################################################################
Organizations:

    # 央行组织定义
    - &CentralBank
        Name: CentralBankMSP
        ID: CentralBankMSP
        MSPDir: ../organizations/ordererOrganizations/centralbank.cbdc.com/msp
        
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('CentralBankMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('CentralBankMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('CentralBankMSP.admin')"
        
        OrdererEndpoints:
            - orderer.centralbank.cbdc.com:7050

    # 央行作为Peer组织
    - &CentralBankPeer
        Name: CentralBankPeerMSP
        ID: CentralBankPeerMSP
        MSPDir: ../organizations/peerOrganizations/centralbank.cbdc.com/msp
        
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('CentralBankPeerMSP.admin', 'CentralBankPeerMSP.peer', 'CentralBankPeerMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('CentralBankPeerMSP.admin', 'CentralBankPeerMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('CentralBankPeerMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('CentralBankPeerMSP.peer')"

        AnchorPeers:
            - Host: peer0.centralbank.cbdc.com
              Port: 7051

    # ab1 银行组织
    - &ab1
        Name: ab1MSP
        ID: ab1MSP
        MSPDir: ../organizations/peerOrganizations/ab1.cbdc.com/msp
        
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('ab1MSP.admin', 'ab1MSP.peer', 'ab1MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('ab1MSP.admin', 'ab1MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('ab1MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('ab1MSP.peer')"

        AnchorPeers:
            - Host: peer0.ab1.cbdc.com
              Port: 8051

    # bb1 银行组织
    - &bb1
        Name: bb1MSP
        ID: bb1MSP
        MSPDir: ../organizations/peerOrganizations/bb1.cbdc.com/msp
        
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('bb1MSP.admin', 'bb1MSP.peer', 'bb1MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('bb1MSP.admin', 'bb1MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('bb1MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('bb1MSP.peer')"

        AnchorPeers:
            - Host: peer0.bb1.cbdc.com
              Port: 9051

################################################################################
#
#   功能定义
#
################################################################################
Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true

    Orderer: &OrdererCapabilities
        V2_0: true

    Application: &ApplicationCapabilities
        V2_5: true

################################################################################
#
#   应用程序配置
#
################################################################################
Application: &ApplicationDefaults
    Organizations:
    
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"

    Capabilities:
        <<: *ApplicationCapabilities

################################################################################
#
#   排序节点配置
#
################################################################################
Orderer: &OrdererDefaults
    OrdererType: etcdraft
    
    Addresses:
        - orderer.centralbank.cbdc.com:7050
    
    EtcdRaft:
        Consenters:
        - Host: orderer.centralbank.cbdc.com
          Port: 7050
          ClientTLSCert: ../organizations/ordererOrganizations/centralbank.cbdc.com/orderers/orderer.centralbank.cbdc.com/tls/server.crt
          ServerTLSCert: ../organizations/ordererOrganizations/centralbank.cbdc.com/orderers/orderer.centralbank.cbdc.com/tls/server.crt
    
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    
    Organizations:
    
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

    Capabilities:
        <<: *OrdererCapabilities

################################################################################
#
#   频道配置
#
################################################################################
Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ChannelCapabilities

################################################################################
#
#   配置文件定义
#
################################################################################
Profiles:

    # 创世区块配置
    cbdc-channelOrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *CentralBank
        Consortiums:
            CBDCConsortium:
                Organizations:
                    - *CentralBankPeer
                    - *ab1
                    - *bb1

    # 频道配置
    cbdc-channelChannel:
        Consortium: CBDCConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *CentralBankPeer
                - *ab1
                - *bb1

    # 应用频道配置（标准Fabric v2.5+做法）
    CBDCChannel:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *CentralBank
            Capabilities: *OrdererCapabilities
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *CentralBankPeer
                - *ab1
                - *bb1
            Capabilities: *ApplicationCapabilities
